# Deformable DETR Configuration for Traffic Object Classification

model:
  name: "deformable_detr"
  backbone: "resnet50"
  num_classes: 10  # Adjust based on your traffic object classes
  num_queries: 100
  pretrained: true
  
dataset:
  type: "balanced"  # or "imbalanced"
  train_data_dir: "data/balanced/train"  # or "data/imbalanced/train"
  val_data_dir: "data/balanced/val"      # or "data/imbalanced/val"
  test_data_dir: "data/balanced/test"    # or "data/imbalanced/test"
  annotation_format: "coco"
  
  # Data augmentation
  transforms:
    train:
      - resize: [800, 1333]
      - horizontal_flip: 0.5
      - normalize: true
    val:
      - resize: [800, 1333]
      - normalize: true

training:
  batch_size: 4
  num_epochs: 150
  learning_rate: 0.0001
  weight_decay: 0.0001
  optimizer: "adamw"
  scheduler: "step"
  
  # Loss configuration
  matcher:
    cost_class: 2
    cost_bbox: 5
    cost_giou: 2
  
  losses:
    class_loss_coef: 2
    bbox_loss_coef: 5
    giou_loss_coef: 2
  
  # Checkpoint settings
  save_every: 10
  save_best: true
  
logging:
  wandb:
    project: "traffic-object-classification"
    name: "deformable-detr-balanced"
  tensorboard: true
  
device: "cuda"  # or "cpu"