# Default configuration for Deformable DETR training
model:
  name: "deformable_detr"
  num_classes: 10
  num_queries: 300
  hidden_dim: 256
  
  # Transformer parameters
  num_encoder_layers: 6
  num_decoder_layers: 6
  num_heads: 8
  dropout: 0.1
  
  # Deformable attention parameters
  num_feature_levels: 4
  num_points: 4
  
  # Pre-trained model
  pretrained_model_name: "SenseTime/deformable-detr"
  freeze_backbone: false

dataset:
  name: "traffic"
  root_dir: "data/traffic"
  train_split: "train"
  val_split: "val"
  test_split: "test"
  
  # Data processing
  image_size: 800
  batch_size: 4  # Smaller batch size for DETR
  num_workers: 4
  shuffle: true
  
  # Data augmentation
  augmentation:
    enabled: true
    horizontal_flip: 0.5
    scale_jitter: [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
    crop_size: [384, 600]
    brightness_contrast: 0.3

training:
  epochs: 150  # DETR typically needs more epochs
  learning_rate: 1e-4
  weight_decay: 1e-4
  
  # Optimizer settings
  optimizer: "adamw"
  lr_backbone: 1e-5  # Lower LR for backbone
  
  # Scheduler settings
  scheduler: "step"
  step_size: 100
  gamma: 0.1
  
  # Training control
  save_every: 10
  eval_every: 5
  early_stopping_patience: 30
  gradient_clip_norm: 0.1  # Lower for DETR

evaluation:
  iou_threshold: 0.5
  confidence_threshold: 0.5
  metrics: ["mAP", "AP50", "AP75", "precision", "recall", "f1"]

# DETR specific loss configuration
loss:
  # Matching costs
  cost_class: 2.0
  cost_bbox: 5.0
  cost_giou: 2.0
  
  # Loss weights
  loss_ce: 2.0      # Classification loss
  loss_bbox: 5.0    # L1 bbox loss
  loss_giou: 2.0    # GIoU loss
  
  # Auxiliary losses
  aux_loss: true
  aux_loss_weight: 1.0
  
  # Focal loss for classification
  focal_loss:
    enabled: true
    alpha: 0.25
    gamma: 2.0

# Class configuration
classes:
  names: [
    "background",
    "car",
    "truck", 
    "bus",
    "motorcycle",
    "bicycle",
    "person",
    "traffic_light",
    "traffic_sign",
    "stop_sign"
  ]
  
  # Class weights for imbalanced datasets
  weights: null

# Paths
paths:
  data_dir: "data"
  output_dir: "outputs"
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  results_dir: "results"

# Logging configuration
logging:
  level: "INFO"
  log_to_file: true
  log_to_console: true
  
  # Weights & Biases
  use_wandb: false
  wandb_project: "traffic-object-detection-detr"
  wandb_entity: null

# Hardware settings
device: "auto"
mixed_precision: true  # DETR benefits from mixed precision
deterministic: false
random_seed: 42

# Post-processing
postprocessing:
  score_threshold: 0.5
  nms_threshold: 0.5
  max_detections: 100